name: Pruebas de Playwright
on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  pruebas:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Instalar dependencias
      run: npm ci
    - name: Instalar navegadores de Playwright
      run: npx playwright install --with-deps
    - name: Iniciar servidor web
      run: npm run dev &
      env:
        CI: true
    - name: Esperar a que el servidor esté listo
      run: npx wait-on http://localhost:5173
    - name: Ejecutar pruebas de Playwright
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: reporte-playwright
        path: playwright-report/
        retention-days: 30
